name: Deploy server

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            export REDIS_ENDPOINT=${{ secrets.REDIS_ENDPOINT }}
            export CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
            cd chatroomz
            git pull
            cd server
            docker-compose down
            docker-compose --project-name chat up -d --build
